# Generated by Django 5.2 on 2025-04-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
